[package]
name = "ecc"
version = "0.1.0"
authors = ["Diogo Jerónimo <diogo10jeronimo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.5"